/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package digitalgui;

import java.awt.event.KeyEvent;

/**
 *
 * @author arabtech
 */
public class TakeVariables extends javax.swing.JFrame {

    int counter = 0;
    Minimize mini = new Minimize();

    /**
     * Creates new form TakeVariables
     */
    public TakeVariables() {
        initComponents();
        this.setTitle("Tabular Minimization");
        jLabel4.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        elements = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel1.setText("Enter MinTerms");

        elements.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elementsActionPerformed(evt);
            }
        });
        elements.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                elementsKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                elementsKeyTyped(evt);
            }
        });

        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 0, 204));

        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("Dont Enter Number > (Bits^2)-1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(elements, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(59, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(elements, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(98, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void elementsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elementsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_elementsActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (counter < mini.nV) {
            jLabel2.setText(String.valueOf(mini.nV-counter-1));
            if (!elements.getText().equals("") && !elements.getText().equals(null) && Integer.parseInt(elements.getText()) < (Math.pow(2, mini.nG - 1))) {
                int num = Integer.parseInt(elements.getText());
                jLabel4.setVisible(false);
                counter++;
                int bits = Integer.bitCount(num);
                mini.groups.get(bits).add(mini.toBinary(num));
                mini.check.get(bits).add(false);
                elements.setText(null);
                if (counter == mini.nV) {
                    TakeDontCare takeDont = new TakeDontCare();
                    takeDont.setVisible(true);
                    takeDont.setLocationRelativeTo(null);
                    this.setVisible(false);
                }
            } else {
                jLabel4.setVisible(true);
                jLabel4.setText("Dont Enter Number > " + String.valueOf((int) Math.pow(2, mini.nG - 1) - 1));
            }
        } else {
            TakeDontCare takeDont = new TakeDontCare();
            takeDont.setVisible(true);
            takeDont.setLocationRelativeTo(null);
            this.setVisible(false);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void elementsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_elementsKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER && !elements.getText().equals("") && !elements.getText().equals(null)) {
            // Enter was pressed. Your code goes here.

            if (counter < mini.nV) {
                jLabel2.setText(String.valueOf(mini.nV-counter-1));
                int num = Integer.parseInt(elements.getText());
                if (num < (Math.pow(2, mini.nG - 1))) {
                    jLabel4.setVisible(false);
                    counter++;
                    int bits = Integer.bitCount(num);
                    mini.groups.get(bits).add(mini.toBinary(num));
                    mini.check.get(bits).add(false);
                    elements.setText(null);
                    if (counter == mini.nV) {
                        TakeDontCare takeDont = new TakeDontCare();
                        takeDont.setVisible(true);
                        takeDont.setLocationRelativeTo(null);
                        this.setVisible(false);
                    }
                } else {
                    jLabel4.setVisible(true);
                    jLabel4.setText("Dont Enter Number > " + String.valueOf((int) Math.pow(2, mini.nG - 1) - 1));
                }
            } else {
                TakeDontCare takeDont = new TakeDontCare();
                takeDont.setVisible(true);
                takeDont.setLocationRelativeTo(null);
                this.setVisible(false);
            }
        }
    }//GEN-LAST:event_elementsKeyPressed

    private void elementsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_elementsKeyTyped
        char txt = evt.getKeyChar();
        if (!Character.isDigit(txt)) {
            evt.consume();
        }
    }//GEN-LAST:event_elementsKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TakeVariables.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TakeVariables.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TakeVariables.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TakeVariables.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TakeVariables().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField elements;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
